name: Convert Latest Uploaded Documents to Markdown
on:
  push:
    paths:
      - 'documents/**'
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # To be able to get changed files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'markitdown[all]'

      - name: Get changed files
        id: changed-files
        run: |
          echo "Finding changed files..."
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep "^documents/" | grep -v "\.md$" || echo "")
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Convert documents to Markdown
        run: |
          echo "Starting conversion..."
          if [ -z "$CHANGED_FILES" ]; then
            echo "No non-markdown documents were changed."
          else
            echo "Files to convert: $CHANGED_FILES"
            python toMarkdown.py "$CHANGED_FILES"
          fi

      - name: List documents directory contents
        run: ls -la documents/

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if git status --porcelain | grep -q "documents/"; then
            echo "Changes detected. Committing..."
            git add documents/
            git commit -m "Convert latest uploaded documents to Markdown"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
